# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'code.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 500)
        Form.setMaximumSize(QtCore.QSize(10000, 500000))
        self.widget_add = QtWidgets.QWidget(Form)
        self.widget_add.setGeometry(QtCore.QRect(100, 0, 149, 213))
        self.widget_add.setObjectName("widget_add")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_add)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_add1 = QtWidgets.QLabel(self.widget_add)
        self.label_add1.setObjectName("label_add1")
        self.verticalLayout_2.addWidget(self.label_add1)
        self.line_add1 = QtWidgets.QLineEdit(self.widget_add)
        self.line_add1.setObjectName("line_add1")
        self.verticalLayout_2.addWidget(self.line_add1)
        self.label_add2 = QtWidgets.QLabel(self.widget_add)
        self.label_add2.setObjectName("label_add2")
        self.verticalLayout_2.addWidget(self.label_add2)
        self.line_add2 = QtWidgets.QLineEdit(self.widget_add)
        self.line_add2.setObjectName("line_add2")
        self.verticalLayout_2.addWidget(self.line_add2)
        self.label_add3 = QtWidgets.QLabel(self.widget_add)
        self.label_add3.setObjectName("label_add3")
        self.verticalLayout_2.addWidget(self.label_add3)
        self.line_add3 = QtWidgets.QLineEdit(self.widget_add)
        self.line_add3.setObjectName("line_add3")
        self.verticalLayout_2.addWidget(self.line_add3)
        self.label_add4 = QtWidgets.QLabel(self.widget_add)
        self.label_add4.setObjectName("label_add4")
        self.verticalLayout_2.addWidget(self.label_add4)
        self.line_add4 = QtWidgets.QLineEdit(self.widget_add)
        self.line_add4.setObjectName("line_add4")
        self.verticalLayout_2.addWidget(self.line_add4)
        self.button_add2 = QtWidgets.QPushButton(self.widget_add)
        self.button_add2.setObjectName("button_add2")
        self.verticalLayout_2.addWidget(self.button_add2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 77, 501))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_add = QtWidgets.QPushButton(self.widget)
        self.button_add.setObjectName("button_add")
        self.verticalLayout.addWidget(self.button_add)
        self.button_del = QtWidgets.QPushButton(self.widget)
        self.button_del.setObjectName("button_del")
        self.verticalLayout.addWidget(self.button_del)
        self.button_change = QtWidgets.QPushButton(self.widget)
        self.button_change.setObjectName("button_change")
        self.verticalLayout.addWidget(self.button_change)
        self.button_search = QtWidgets.QPushButton(self.widget)
        self.button_search.setObjectName("button_search")
        self.verticalLayout.addWidget(self.button_search)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_add1.setText(_translate("Form", "名称"))
        self.label_add2.setText(_translate("Form", "用户名"))
        self.label_add3.setText(_translate("Form", "密码"))
        self.label_add4.setText(_translate("Form", "备注 "))
        self.button_add2.setText(_translate("Form", "添加"))
        self.button_add.setText(_translate("Form", "添加密码"))
        self.button_del.setText(_translate("Form", "删除密码"))
        self.button_change.setText(_translate("Form", "查询密码"))
        self.button_search.setText(_translate("Form", "修改密码"))




